#! /bin/sh

# script/my-dirname - script for extracting dirname, hopefully portably across various systems.
# Copyright (C) 2012 Alan Manuel K. Gloria
#
# This file is part of Letterfall.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

as_dir=${1-.}

# Portable dirname
if (as_dir=`dirname -- /` && test "X${as_dir}" = X/) > /dev/null 2>&1; then
  as_dirname=dirname
else
  as_dirname=false
fi

${as_dirname} $1 ||
echo $1 | sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{
            s//\1/
            q
          }
          /^X\(\/\/\)[^/].*/{
            s//\1/
            q
          }
          /^X\(\/\/\)$/{
            s//\1/
            q
          }
          /^X\(\/\).*/{
            s//\1/
            q
          }
          s/.*/./; q'

